EUREKA.CONST.PORT: 8759
EUREKA.CONST.PATH: /gtw
EUREKA.APPLICATION.NAME: spring-cloud-gateway-server
server:
  port: ${EUREKA.CONST.PORT}
  servlet:
    context-path: ${EUREKA.CONST.PATH}
spring:
  application:
    name: ${EUREKA.APPLICATION.NAME}
